### PR TITLE
fixed kfac function import and calls

### PR DESCRIPTION
**Pull request by alexanderimanicowenrivers**
import kfac using "!pip install 'kfac[tensorflow]'"

### CODE REVIEW

**Comment by alexanderimanicowenrivers** [comment]
image

I have signed a google CLA with this github username, so I am unsure why the commit check failed....

**Comment by sracaniere** [comment]
Thanks for your suggested contribution.
I'm not sure what the error message means either. I'll look for someone who can try and explain on my side, but in the mean time could you try to click the link with the agreement that was suggested to you, and sign it again (if you agree with it)?

**Comment by alexanderimanicowenrivers** [comment]
Hey, I have done that again.  Thanks for the repo by the way!!! 


screenshot 2018-12-05 at 14 55 37
screenshot 2018-12-05 at 14 55 32

**Comment by sracaniere** [comment]
I hope you find the code useful :)
Are you able to commit now that you have (re-)signed the agreement?

**Pull request closed without merging**
